name: Deploy CDK

on:
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies (IAC)
        run: |
          cd iac
          npm ci

      - name: Lint and Format IAC (TypeScript)
        run: |
          cd iac
          npm run lint
          npx prettier --check 'lib/**/*.ts' 'bin/**/*.ts'

      - name: Lint and Format SRC (Python)
        run: |
          pip install pylint
          pylint src/test-deployment

  synth:
    name: Build (Synth)
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd iac
          npm ci

      - name: Synth
        run: |
          cd iac
          npx cdk synth

      - name: Upload CDK Assembly
        uses: actions/upload-artifact@v4
        with:
          name: cdk-out
          path: iac/cdk.out

  deploy:
    name: Deploy
    needs: synth
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Download CDK Assembly
        uses: actions/download-artifact@v4
        with:
          name: cdk-out
          path: iac/cdk.out

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy
        run: |
          cd iac
          npm install -g aws-cdk
          cdk deploy --app cdk.out --all --require-approval never
